/* #undef AUTH_MODE_CERT */
#define AUTH_MODE_KEY
#define AUTH_WITH_NOTLS
#define GATEWAY_ENABLED
#define GATEWAY_AUTOMATION_ENABLED
/* #undef COAP_COMM_ENABLED */
#define OTA_MQTT_CHANNEL
/* #undef SYSTEM_COMM */
#define EVENT_POST_ENABLED
#define ACTION_ENABLED
#define DEV_DYN_REG_ENABLED
#define LOG_UPLOAD
/* #undef IOT_DEBUG */
/* #undef DEBUG_DEV_INFO_USED */
/* #undef AT_TCP_ENABLED */
/* #undef AT_UART_RECV_IRQ */
/* #undef AT_OS_USED */
/* #undef AT_DEBUG */
/* #undef OTA_USE_HTTPS */
#define GATEWAY_ENABLED
//#define MULTITHREAD_ENABLED
/* #undef GATEWAY_DYN_BIND_SUBDEV_ENABLED */
/* #undef ASR_ENABLED */
/* #undef RESOURCE_UPDATE_ENABLED */
#define WIFI_CONFIG_ENABLED
#define KGMUSIC_ENABLED
